#버전 카탈로그 설명:
#- https://developer.android.com/build/migrate-to-catalogs?hl=ko
#- https://cjconnect.atlassian.net/issues/?filter=10229
[versions]
agp = "8.2.2"
org-jetbrains-kotlin-android = "1.9.22"
hilt-android = "2.50"


[libraries]
hilt = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt-android" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt-android" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "org-jetbrains-kotlin-android" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "org-jetbrains-kotlin-android"}
hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hilt-android"}